name: gradcam1d
channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1
  - torchvision=0.16
  - torchaudio=2.1
  - cpuonly
  - captum=0.7
  - pandas=2.2
  - numpy=1.26
  - pyyaml=6.0
  - biopython=1.83
  - snakemake=7.32
  - h5py=3.9
  - matplotlib=3.8
  - tqdm=4.66
  - blast=2.14
